openapi: 3.0.1
info:
  title: Weibo Hotpoint
  version: v1
  description: Using API for Weibo hotpoint
servers:
  - url: https://v3.alapi.cn
paths:
  /api/new/wbtop:
    get:
      summary: Get Weibo Hot Topics
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
